[project]
name = "transcription"
version = "0.1.0"
requires-python = ">=3.12"
scripts = { transcription = "main:main" }

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

