# Application Settings
app:
  name: "Audio Processor"
  version: "1.0.0"
  debug: false

# File Processing
processing:
  watch_folder: "{{WATCH_FOLDER}}"
  processed_folder: "{{PROCESSED_FOLDER}}"
  error_folder: "{{ERROR_FOLDER}}"
  output_folder: "{{OUTPUT_FOLDER}}"
  file_stability_wait: 10  # seconds
  supported_formats: [".mp3", ".wav", ".m4a", ".mp4", ".mov"]
  recursive_watch: true
  prompt_filenames: ["instructions.md", ".instructions.md"]

# External APIs
deepgram:
  model: "nova-2"
  features:
    punctuate: true
    paragraphs: true
    speaker_diarize: true
    smart_format: true
    utt_split: true
    numerals: true

openai:
  model: "gpt-4o"
  temperature: 0.7
  max_tokens: 4000

# Prompt file resolution (folder overrides)
prompt_files:
  summary_candidates: ["instructions.md", "summary.md", ".instructions.md"]
  naming_candidates: ["naming.md", ".naming.md"]
  validation_candidates: ["filename-validation.md", ".filename-validation.md"]

# Web Interface
web:
  host: "127.0.0.1"
  port: 8000
  auto_reload: false

# Logging
logging:
  level: "INFO"
  max_file_size: "10MB"
  backup_count: 5

# AI Prompts
prompts:
  summary: |
    Summarise the following meeting transcript clearly and concisely for a professional audience.

    Output: well‑structured Markdown with an Executive Summary (≤ 300 words), key discussion points, advice given, action items (owner + task + due date if present), entities/roles, and notable dates/events. Use neutral tone, bullets where suitable, and only facts present in the transcript. Flag unknowns as "unspecified". Australian context unless otherwise stated.

    Original Filename: {original_filename}
    Duration (minutes): {duration_minutes}
    Transcript: {transcript}

  action_items: |
    Extract all action items and next steps from this legal meeting transcript.
    
    Focus on:
    - Specific tasks assigned to individuals
    - Follow-up meetings or calls to be scheduled
    - Documents to be prepared or reviewed
    - Information to be gathered or verified
    - Deadlines or time-sensitive matters
    - Client homework or responsibilities
    
    Format as:
    - **[Person/Role]:** [Task description] (Due: [date if mentioned, otherwise "TBD"])
    
    Only include explicit tasks and commitments, not general discussion points.
    If no specific action items are mentioned, state "No specific action items identified in transcript."
    
    Transcript: {transcript}
    
  naming_extraction: |
    Create a complete filename for this file relating to a legal meeting. Use the original filename and transcript as the source of information to construct a well-formed file name following the conventions and style set out below.

    **Filename Format:** [Date] [Type] with [Names] re [Topic] - [Duration]min [MatterNumber]

    Where:
      [DATE] - This is the date of the meeting. This can usually be extracted from the original filename. It is usually a 8-digit date in the format YYYYMMDD. This is NOT the date that the file is transcribed.

      [Type] - This is the type of meeting that has been recorded and transcribed. Common types of meeting are 'Calls', 'Meetings', 'Interviews', 'Presentations'. This can usually be extracted from the original filename. However, sometimes it needs to be determined from the transcript itself. Common shorthand includes 'TA' for 'Call' and 'MTG' for 'Meeting'.

      [Names] - These are the names of people involved in the meeting. The original filename usually includes at least one Name. Sometimes it is a single name (e.g. John), and sometimes it is a full first and second name (e.g. 'John Smith'). Sometimes it is more than one name, (e.g. John and Karen).

      [Topic] - This is the main topic of the meeting. This can usually be extracted from the original filename (e.g. 're estate administration'). However, if there is no main topic in the original file name, you will need to use the transcript to extract the topic.

      [Duration] - This is the duration of the meeting in minutes. This can usually be extracted from the original filename.

      [MatterNumber] - This is the 5-digit matter number that corresponds to our practice management system. You can identify it by square brackets or underscores (e.g. [12345] or _12345_). They are usualy at the end of the original filename.

    **Good Examples:**
    - 20250526 TA with Michael Murray re Data Patents - 15min [12345]
    - 20250523 TA with Anthony re Pickles Schoolwear Sale - 30min [52634]
    - 20250715 Call with Michael Fox re Tax Advice - 8min

    **CRITICAL ERRORS TO AVOID:**
    - ❌ "20250720 20250526 TA Michael Murray" (duplicate dates - use ONLY the original file date)
    - ❌ "TA Anthony re Pickles Schoolwear sale - Processed" (never add "Processed")
    - ❌ "Call with Rob Veitch and Veitch" (duplicate last names)
    - ❌ "re Michael Fox re Michael Fox" (person as topic)

    **RULES:**
    1. Use ONLY the date from the original filename (not today's date)
    2. NEVER add "Processed" or similar suffixes or prefixes
    3. Extract participants and topic from transcript when necessary
    4. Keep it clean and professional

    Return ONLY the complete filename, nothing else:

    20250526 TA with Michael Murray re Data Patents - 15min [12534]

    **Original Filename:** {original_filename}
    **Transcript:** {transcript}

  filename_validation: |
    Review this filename and fix any issues. Make it professional and logical.

    **Proposed:** {proposed_filename}
    **Original:** {original_filename}

    **CRITICAL ISSUES TO FIX:**
    - ❌ Duplicate dates: "20250720 20250526 TA" → "20250526 TA"
    - ❌ "Processed" suffix: "re Topic - Processed" → "re Topic"
    - ❌ Duplicate names: "John Smith and Smith" → "John Smith"
    - ❌ Person as topic: "re John Smith" → use actual topic or remove
    - ❌ Duplicate words: "re re Topic" → "re Topic"

    If the filename has issues, return ONLY the corrected filename.
    If the filename is fine, return ONLY the word "VALID".

    Examples:
    - Input: "20250720 20250526 TA Michael Murray" → Output: "20250526 TA Michael Murray"
    - Input: "20250526 TA Anthony re Pickles - Processed" → Output: "20250526 TA Anthony re Pickles"
    - Input: "20250526 TA Michael Murray re Data Patents - 15min" → Output: "VALID"
